# Generated by Django 5.1.2 on 2025-05-04 07:14

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Portada', models.ImageField(upload_to='')),
                ('Logotipo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ingenierias', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INGENIERÍA INDUSTRIAL', 'Ingeniería Industrial'), ('INGENIERÍA INDUSTRIAL MIXTA', 'Ingeniería Industrial MIXTA'), ('INGENIERÍA EN GESTIÓN EMPRESARIAL', 'Ingeniería en Gestión Empresarial'), ('INGENIERÍA EN GESTIÓN EMPRESARIAL MIXTA', 'Ingeniería en Gestión Empresarial MIXTA'), ('INGENIERÍA EN SISTEMAS COMPUTACIONALES', 'Ingeniería en Sistemas Computacionales'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA EN INDUSTRIAS ALIMENTARIAS', 'Ingeniería en Industrias Alimentarias'), ('INGENIERÍA EN AGRONOMÍA', 'Ingeniería en Agronomía'), ('INGENIERÍA EN INTELIGENCIA ARTIFICIAL', 'Ingeniería en Inteligencia Artificial'), ('INGENIERÍA EN DESARROLLO DE APLICACIONES', 'Ingeniería en Desarrollo de Aplicaciones')], max_length=324)),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('estado', models.CharField(choices=[('Habilitada', 'Habilitada'), ('Deshabilitada', 'Deshabilitada')], default='Habilitada', max_length=20)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducacionDual.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('Apellidos', models.CharField(blank=True, max_length=70, null=True)),
                ('Carrera', models.CharField(blank=True, choices=[('INGENIERÍA INDUSTRIAL', 'Ingeniería Industrial'), ('INGENIERÍA INDUSTRIAL MIXTA', 'Ingeniería Industrial MIXTA'), ('INGENIERÍA EN GESTIÓN EMPRESARIAL', 'Ingeniería en Gestión Empresarial'), ('INGENIERÍA EN GESTIÓN EMPRESARIAL MIXTA', 'Ingeniería en Gestión Empresarial MIXTA'), ('INGENIERÍA EN SISTEMAS COMPUTACIONALES', 'Ingeniería en Sistemas Computacionales'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA EN INDUSTRIAS ALIMENTARIAS', 'Ingeniería en Industrias Alimentarias'), ('INGENIERÍA EN AGRONOMÍA', 'Ingeniería en Agronomía'), ('INGENIERÍA EN INTELIGENCIA ARTIFICIAL', 'Ingeniería en Inteligencia Artificial'), ('INGENIERÍA EN DESARROLLO DE APLICACIONES', 'Ingeniería en Desarrollo de Aplicaciones')], max_length=50, null=True)),
                ('Fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('Genero', models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Semestre', models.CharField(blank=True, choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=1, null=True)),
                ('NoControl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducacionDual.convocatoria')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducacionDual.userprofile')),
            ],
            options={
                'unique_together': {('alumno', 'convocatoria')},
            },
        ),
    ]
