# Generated by Django 5.1.2 on 2024-11-10 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionDual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('Correo_inst', models.EmailField(blank=True, max_length=70, null=True)),
                ('Carrera', models.CharField(blank=True, choices=[('INGENIERÍA INDUSTRIAL', 'Ingeniería Industrial'), ('INGENIERÍA EN GESTIÓN EMPRESARIAL', 'Ingeniería en Gestión Empresarial'), ('INGENIERÍA EN SISTEMAS COMPUTACIONALES', 'Ingeniería en Sistemas Computacionales'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA EN INDUSTRIAS ALIMENTARIAS', 'Ingeniería en Industrias Alimentarias'), ('INGENIERÍA EN AGRONOMÍA', 'Ingeniería en Agronomía'), ('INGENIERÍA EN INTELIGENCIA ARTIFICIAL', 'Ingeniería en Inteligencia Artificial'), ('INGENIERÍA EN DESARROLLO DE APLICACIONES', 'Ingeniería en Desarrollo de Aplicaciones')], max_length=50, null=True)),
                ('Fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('Genero', models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=10, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('Semestre', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1, null=True)),
                ('NoControl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
