# Generated by Django 5.1.2 on 2024-11-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionDual', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Apellidos',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
