# Generated by Django 5.1.2 on 2025-05-02 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionDual', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('estado', models.CharField(choices=[('habilitada', 'Habilitada'), ('deshabilitada', 'Deshabilitada')], default='habilitada', max_length=20)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducacionDual.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('interesado', 'Interesado'), ('postulado', 'Postulado'), ('rechazado', 'Rechazado'), ('aceptado', 'Aceptado')], default='interesado', max_length=20)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducacionDual.userprofile')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducacionDual.convocatoria')),
            ],
            options={
                'unique_together': {('alumno', 'convocatoria')},
            },
        ),
    ]
