# Generated by Django 5.1.2 on 2025-05-02 04:47

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionDual', '0003_convocatoria_postulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='estado',
            field=models.CharField(choices=[('Habilitada', 'Habilitada'), ('Deshabilitada', 'Deshabilitada')], default='habilitada', max_length=20),
        ),
    ]
