# Generated by Django 5.1.2 on 2025-05-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionDual', '0003_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Semestre',
            field=models.CharField(blank=True, choices=[('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=2, null=True),
        ),
    ]
