# Generated by Django 5.1.2 on 2025-05-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionDual', '0004_alter_convocatoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
