# Generated by Django 5.1.2 on 2025-05-02 20:24

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionDual', '0006_convocatoria_ingenierias_alter_convocatoria_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='ingenierias',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('INGENIERÍA INDUSTRIAL', 'Ingeniería Industrial'), ('INGENIERÍA INDUSTRIAL MIXTA', 'Ingeniería Industrial MIXTA'), ('INGENIERÍA EN GESTIÓN EMPRESARIAL', 'Ingeniería en Gestión Empresarial'), ('INGENIERÍA EN GESTIÓN EMPRESARIAL MIXTA', 'Ingeniería en Gestión Empresarial MIXTA'), ('INGENIERÍA EN SISTEMAS COMPUTACIONALES', 'Ingeniería en Sistemas Computacionales'), ('INGENIERÍA AMBIENTAL', 'Ingeniería Ambiental'), ('INGENIERÍA EN INDUSTRIAS ALIMENTARIAS', 'Ingeniería en Industrias Alimentarias'), ('INGENIERÍA EN AGRONOMÍA', 'Ingeniería en Agronomía'), ('INGENIERÍA EN INTELIGENCIA ARTIFICIAL', 'Ingeniería en Inteligencia Artificial'), ('INGENIERÍA EN DESARROLLO DE APLICACIONES', 'Ingeniería en Desarrollo de Aplicaciones')], max_length=324),
        ),
    ]
