# Generated by Django 5.1.2 on 2025-05-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducacionDual', '0007_alter_convocatoria_ingenierias'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
