from django.urls import path
from django.contrib.auth import views as auth_views
from EducacionDual import views


urlpatterns = [
    path('', views.QueEs, name='QueEs'),
    path('login/', views.login_view, name='login'),  # URL para login de alumnos
    path('login_admin_view/', views.login_admin_view, name='login_admin'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='EducacionDual/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='EducacionDual/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='EducacionDual/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='EducacionDual/password_reset_complete.html'), name='password_reset_complete'),
    path('Convocatorias/', views.Convocatorias, name='Convocatorias'),
    path('Normatividad/', views.Normatividad, name='Normatividad'),
    path('Galeria/', views.Galeria, name='Galeria'),
    path('Empresas/', views.Empresas_Prin, name='Empresas'),
    path('empresas/<int:empresa_id>/', views.Empresa_Detalle, name='empresa_detalle'),
    path('baseAdmin/', views.baseAdmin, name='baseAdmin'),  # Dashboard de admin
    path('principalAdmin/', views.principalAdmin, name='principalAdmin'),
    path('logout/', views.logout_view, name='logout'),
    path('ver-pdf/<int:documento_id>/', views.mostrar_pdf, name='mostrar_pdf'),
    path('Registrate', views.register_user_view, name='Registrate'),
    path('principalAlumno', views.principalAlumno, name='principalAlumno'),
    path('admin_profile/', views.admin_profile_view, name='admin_profile'),
    path('admin_profile/edit/', views.edit_admin_profile_view, name='edit_admin_profile'),
    path('lista_Alumnos/', views.lista_Alumnos_view, name='lista_Alumnos'),
    path('Alumno_perfil_detalle/<int:user_id>/', views.Alumno_perfil_detalle_view, name='Alumno_perfil_detalle'),
    path('edit_Alumno/', views.edit_Alumno_profile_view, name='edit_Alumno'),
    path('complete_profile/', views.complete_profile, name='complete_profile'),
    path('Alumno_perfil/', views.Alumno_perfil_view, name='Alumno_perfil'),
    path('lista_empresas/', views.empresas_detalle_view, name='lista_empresas'),
    path('crear_empresa/', views.crear_empresa, name='crear_empresa'),
    path('editar_empresa/<int:empresa_id>/', views.editar_empresa_view, name='editar_empresa'),
    path('eliminar_empresa/<int:empresa_id>/', views.eliminar_empresa_view, name='eliminar_empresa'),
    path('documentos/', views.lista_documentos_view, name='lista_documentos'),
    path('documentos/crear/', views.crear_documento_view, name='crear_documento'),
    path('documentos/<int:documento_id>/editar/', views.editar_documento_view, name='editar_documento'),
    path('documentos/<int:documento_id>/eliminar/', views.eliminar_documento_view, name='eliminar_documento'),
    path('convocatoriasAdmin/', views.ConvocatoriaListView.as_view(), name='convocatoria_list'),
    path('convocatoriasAdmin/<int:pk>/', views.ConvocatoriaDetailView.as_view(), name='convocatoria_detail'),
    path('convocatoriasAdmin/nueva/', views.ConvocatoriaCreateView.as_view(), name='convocatoria_create'),
    path('convocatoriasAdmin/<int:pk>/editar/', views.ConvocatoriaUpdateView.as_view(), name='convocatoria_update'),
    path('convocatoriasAdmin/<int:pk>/eliminar/', views.ConvocatoriaDeleteView.as_view(), name='convocatoria_delete'),
    path('convocatorias/', views.convocatorias_alumno, name='convocatorias_alumno'),
    path('convocatoria/<int:convocatoria_id>/', views.convocatoria_detalle_alumno, name='convocatoria_detalle_alumno'),
    path('postularse/<int:convocatoria_id>/', views.postularse, name='postularse'),
    path('postulacionAdmin/', views.todas_las_postulaciones, name='todas_las_postulaciones'),
    path('postulacionAdmin/<int:postulacion_id>/', views.postulacion_detalle, name='postulacion_detalle'),
    path('mis_postulaciones/', views.mis_postulaciones, name='mis_postulaciones'),
    path('postulacion/eliminar/<int:postulacion_id>/', views.eliminar_postulacion, name='eliminar_postulacion'),
    path('alumno/eliminar/<int:alumno_id>/', views.eliminar_alumno, name='eliminar_alumno'),
    path('convocatoria/publica/<int:convocatoria_id>/', views.detalle_convocatoria, name='detalle_convocatoria'),
    path('ingenierias/', views.lista_ingenierias, name='lista_ingenierias'),
    path('ingenierias/nueva/', views.crear_ingenieria, name='crear_ingenieria'),
    path('ingenierias/editar/<int:pk>/', views.editar_ingenieria, name='editar_ingenieria'),
    path('ingenierias/eliminar/<int:pk>/', views.eliminar_ingenieria, name='eliminar_ingenieria'),
    path('proyectos/', views.lista_proyectos, name='lista_proyectos'),
    path('proyectos/nuevo/', views.crear_proyecto, name='crear_proyecto'),
    path('proyectos/editar/<int:pk>/', views.editar_proyecto, name='editar_proyecto'),
    path('proyectos/eliminar/<int:pk>/', views.eliminar_proyecto, name='eliminar_proyecto'),
    path('evidencias/', views.lista_evidencias, name='lista_evidencias'),
    path('evidencias/nueva/', views.crear_evidencia, name='crear_evidencia'),
    path('evidencias/editar/<int:pk>/', views.editar_evidencia, name='editar_evidencia'),
    path('evidencias/eliminar/<int:pk>/', views.eliminar_evidencia, name='eliminar_evidencia'),
    path('galeriaAdmin/', views.GaleriaAdmin, name='galeria_Admin'),
    
    path('galeria/empresa/<int:empresa_id>/', views.Galeria_ingenierias , name='galeria_empresa_detalle'),
    path('galeria/empresa/<int:empresa_id>/ingenieria/<int:ingenieria_id>/', views.Galeria_evidencias, name='galeria_empresa_ingenieria_detalle'),

]
